### ISSUE TITLE
Issue while trying to open project

### ISSUE THREAD

**Issue by necomadev** [kingdom-of-ds-hacking/CTRMap-CE#5]
Yo I wanted to use this program and I followed all the steps given in a youtube tutorial. The version the youtuber used was outdated so I though updating might be the solution but it wasn't. I hope that someone can help me with this.
![Screenshot_46](https://github.com/kingdom-of-ds-hacking/CTRMap-CE/assets/62795045/7f508d25-93bb-44b7-9ab6-fc77ee988b4d)

**Comment by HelloOO7** [comment]
The "game data path is invalid" error appears if the file pointed to by the `VFSBase` configuration key in the .cmproj file points to a non-existent location.

This can happen if, for example, you defined a game binding and deleted or moved the directory afterwards. The issue should disappear if you create a new project using a valid path, or redefine the `VFSBase` key to another location in the existing .cmproj manually.

**Comment by HelloOO7** [comment]
Closed due to no further activity.
